GET http://localhost:3000/

### Check DB connection 
GET http://localhost:3000/test-connection

### Get all Students
GET http://localhost:3000/api/students

### Get single student
GET http://localhost:3000/api/students/2

### Create single student
POST  http://localhost:3000/api/students/
Content-Type: application/json

{
    "firstname": "Dominykas",
    "lastname": "Simaitis",
    "email": "DOmSim@bit.lt",
    "created": "2024-01-27"
}
### update student info
PUT  http://localhost:3000/api/students/3
Content-Type: application/json

{
    "firstname": "dziaugiuosi",
    "lastname": "Bit`e",
    "email": "dziaugsmas@bit.lt",
    "created": "2024-01-26"
}


### Delete student
DELETE  http://localhost:3000/api/students/1

